language: go

go:
  - 1.4
  - 1.5
  - tip

sudo: false

before_install:
  - go get github.com/tools/godep
  - godep restore

script:
  - go test -v ./...

notifications:
  irc:
    channels:
      - "irc.freenode.net#chihaya"
    use_notice: true
    skip_join: true
    on_success: always
    on_failure: always
  email: false
