language: go
go:
- 1.8
sudo: false
install:
- go get -t ./...
- go get -u github.com/golang/lint/golint
- go get -u golang.org/x/tools/cmd/goimports
script:
- go test -v $(go list ./... | grep -v /vendor/)
- go vet $(go list ./... | grep -v /vendor/)
- diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(printf "")
- (for d in $(go list ./... | grep -v /vendor/); do diff <(golint $d) <(printf "") || exit 1;  done)
notifications:
  irc:
    channels:
    - irc.freenode.net#chihaya
    use_notice: true
    skip_join: true
    on_success: always
    on_failure: always
  email: false
