# Copyright 2016 The Chihaya Authors. All rights reserved.
# Use of this source code is governed by the BSD 2-Clause license,
# which can be found in the LICENSE file.

chihaya:
  tracker:
    announce: 10m
    min_announce: 5m
    announce_middleware:
      - prometheus
      - store_client_validation
      - store_create_on_announce
    scrape_middleware:
      - prometheus
      - store_client_validation

  servers:
    - name: store
      config:
        addr: localhost:6880
        request_timeout: 10s
        read_timeout: 10s
        write_timeout: 10s
        client_store: memory
        ip_store: memory
        peer_store: memory
        peer_store_config:
          gcAfter: 30m
          shards: 1

    - name: http
      config:
        addr: localhost:6881
        request_timeout: 10s
        read_timeout: 10s
        write_timeout: 10s

    - name: udp
      config:
        addr: localhost:6882
